### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Almad** [grncdr/uri-template#10]
There is no LICENSE file in the repository, nor is `license` field used in `package.json`.

That makes the package tricky to use.

**Comment by grncdr** [comment]
Thanks for pointing this out, it's been fixed now :+1:

**Comment by Almad** [comment]
@grncdr Thanks!

That said, I totally vote for having `"license": "MIT"` in `package.json` as well. It makes things much easier for review! :)

**Comment by grncdr** [comment]
it should be there

**Comment by grncdr** [comment]
https://github.com/grncdr/uri-template/blob/v1.0.0/package.json#L30

**Comment by andreineculau** [comment]
I'll bookmark this commit.
Adding a license file bumps version from 0.4.1 to 1.0.0.
The version change make sense, Stephen, I support it, but you have to admit
it is funny :)

@Almad if you use this library, then it's official - I can add "did work
for apiary.io" on my CV ;)

On Thu, Jan 15, 2015 at 4:34 PM, Stephen Sugden <notifications@github.com>
wrote:

> https://github.com/grncdr/uri-template/blob/v1.0.0/package.json#L30
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grncdr/uri-template/issues/10#issuecomment-70103374>.
>



-- 
andreineculau.com <http://www.andreineculau.com>

**Comment by grncdr** [comment]
I considered a patch version, but nothing has changed in this lib for nearly 2 years seems like I can rule out wild API changes at this point! :laughing:

p.s. - I didn't notice the apiary connection, funny because I've just been looking at using it for work ;)

**Comment by andreineculau** [comment]
Apiary (both the service and the people) rock big time, i can also recommend for-GET/katt but i am biased in both cases :)

**Comment by Almad** [comment]
@andreineculau heh, well, you know what my opinion about that one is ;)
@grncdr Let us know how it went :)
