### ISSUE TITLE
The "pct-encode" dependency is problematic from legal point of view

### ISSUE THREAD

**Issue by odzb** [grncdr/uri-template#11]
The "pct-encode" module doesn't include a LICENSE file, which makes it illegal to redistribute (that is, to include into a web app using Browserify). This is a big issue, as it forces us to look for a replacement for "uri-template" or consider writing our own URI templating module.

**Comment by andreineculau** [comment]
Thanks. I'll add the LICENSE to `publishConfig/files` later today, if Stephen doesn't get to it first.

**Comment by odzb** [comment]
Thanks a lot! I didn't notice that both modules are from the same author :)

**Comment by grncdr** [comment]
`pct-encode` now has a proper license as well, so you should be good to go. Re-open the issue if there's something wrong.

**Comment by andreineculau** [comment]
Both (all) packages should publish the LICENSE file as well (see 355fbaa). From a legal point of view it's not enough 1) if the source code includes one 2) if package.json says "MIT", "BSD", etc

But I'm not going to reopen the issue, if @odzb is fine without.

**Comment by grncdr** [comment]
Sure, it's published on

**Comment by odzb** [comment]
I see that LICENSE files are present in both uri-template 1.0.0 and pct-encode 1.0.2 when fetched from NPM. So all is good! Thank you guys!

**Comment by grncdr** [comment]
:+1:
