### ISSUE TITLE
NPM warning on fresh versions of Node

### ISSUE THREAD

**Issue by odzb** [grncdr/uri-template#12]
Here's what I get on my Node 4.0.0:

npm WARN engine uri-template@1.0.0: wanted: {"node":"~0.10.4"} (current: {"node":"4.0.0","npm":"2.14.2"})

Maybe it's time to change to ">=0.10.4"?

**Comment by kalupa** [comment]
node 0.10.4 is > 3 years old. Is there something specific about this version this module depends on?

released on 2013.04.11https://nodejs.org/en/blog/release/v0.10.4/

**Comment by grncdr** [comment]
Fixed in `v1.0.1`... not sure why this sat open so long.
