### ISSUE TITLE
Existing pct-encoding in values for reserved {+} or fragment {#} expansion must NOT be re-encoded

### ISSUE THREAD

**Issue by JohnBrinkman** [grncdr/uri-template#15]
Expanding:
`{"uri": "http://foo/bar?message=hello%20world"}`
with the template: 
`{+uri}`
must result in:
`"http://foo/bar?message=hello%20world"`

Not

`"http://foo/bar?message=hello%2520world"`

From: https://tools.ietf.org/html/rfc6570#section-3.2.1
"Note that the percent character ("%") is only allowed
as part of a pct-encoded triplet and only for reserved/fragment
expansion: in all other cases, a value character of "%" MUST be pct-
encoded as "%25" by variable expansion."

**Comment by grncdr** [comment]
A fix has been published in `v1.0.1`, thanks for reporting this!

**Comment by JohnBrinkman** [comment]
I have re-tested and it works perfectly.  Thanks!
