### ISSUE TITLE
Error when running example in readme

### ISSUE THREAD

**Issue by gellati** [grncdr/uri-template#16]
I am trying to run the example in the [readme](https://github.com/grncdr/uri-template/blob/master/README.md)

    var parser = require('uri-template');

    var tpl = parser.parse('/{year}/{month}/{day}{?orderBy,direction}');

    tpl.expand({ year: 2006, month: 6, day: 6 }); // /2006/6/6

    tpl.expand({ year: 2006, month: 6, day: 6, orderBy: 'size' }); // /2006/6/6?orderBy=size

    tpl.expand({ year: 2006, month: 6, day: 6, orderBy: 'time', direction: 'asc' }); // /2006/6/6 orderBy=time&direction=asc

    var queryTpl = parser.parse('/search{?q,*otherParams}');
    queryTpl.expand({ q: 'Bigger office', otherParams: { prefer: "Sterling's office", accept: "Crane's office" }}); // /search?q=Bigger%20office&prefer=Sterling%27s%20office&accept=Crane%27s%20office

I run this with

    node script.js

but I get this error from the line beginning with  `var queryTpl`:

    <path_to>/node_modules/uri-template/index.js:673
            throw new this.SyntaxError(
        ^
    SyntaxError: Expected "(", "," or "}" but "o" found.

Could you please tell why this error is given?

**Comment by andreineculau** [comment]
There was a typo in the README, which I have just fixed.
It should have read `otherParams*` not `*otherParams`.

Thank you!

**Comment by gellati** [comment]
Now it works, thanks!
