### ISSUE TITLE
Multiple `{?query}` expansions expand incorrectly for empty values

### ISSUE THREAD

**Issue by evert** [grncdr/uri-template#20]
The RFC states:

> append "?" to the result string if this is the first defined value or append "&" thereafter;

Given a templated uri such as:

    `https://example/{?foo}{?bar}`

And a value of `""` for foo and `"zim"` for bar

This will get expanded to:

    `https://example.org/?foo=?bar=zim

This only appears to be the case if the first entry is empty.

**Comment by evert** [comment]
Seems to be due to this:

https://github.com/grncdr/uri-template/issues/20

**Comment by grncdr** [comment]
I think you are misreading the RFC. With more context (emphasis mine):

> For each defined variable **in the variable-list**:
>
>   o  append "?" to the result string if this is the first defined value
>      or append "&" thereafter;
>
>   o  if the variable has a simple string value or no explode modifier
>      is given, append the variable name (encoded as if it were a
>      literal string) and an equals character ("=") to the result
>      string; and,
>
>   o  perform variable expansion, as defined in Section 3.2.1, with the
>      allowed characters being those in the unreserved set.

The variable-list here does refer to all variables in the entire template, but the variable list of the current expansion.

Consider this template: `https://example/{document}{?format}`. Expanding this with the vars `document=foo` and `format=pdf` should **not** expand to `https://example/foo&format=pdf`.

**Comment by grncdr** [comment]
I corrected a "does refer" -> "does not refer" in the original posting. Sorry if you got a confusing e-mail notification 😄
