### ISSUE TITLE
Objects contains unsupported key warning for valid OpenApi schema.

### ISSUE THREAD

**Issue by armen-ch** [grncdr/uri-template#23]
PS C:\Pact\securities-provider> dredd .\oasexample.yaml http://127.0.0.1:8081  --dry-run
(node:13444) Warning: Accessing non-existent property 'padLevels' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
warn: API description parser warning in C:\Pact\securities-provider\oasexample.yaml:14 (from line 14 column 1 to column 5): 'OpenAPI Object' contains unsupported key 'tags'
warn: API description parser warning in C:\Pact\securities-provider\oasexample.yaml:22 (from line 22 column 7 to column 11): 'Operation Object' contains unsupported key 'tags' (2 occurances)
warn: API description parser warning in C:\Pact\securities-provider\oasexample.yaml:50 (from line 50 column 9 to column 14): 'Parameter Object' contains unsupported key 'style' (3 occurances)
warn: API description parser warning in C:\Pact\securities-provider\oasexample.yaml:61 (from line 61 column 11 to column 18): 'Schema Object' contains unsupported key 'minimum' (2 occurances)
warn: API description parser warning in C:\Pact\securities-provider\oasexample.yaml:63 (from line 63 column 11 to column 17): 'Schema Object' contains unsupported key 'format' (7 occurances)
warn: API description parser warning in C:\Pact\securities-provider\oasexample.yaml:71 (from line 71 column 11 to column 18): 'Schema Object' contains unsupported key 'maximum'
warn: API description parser warning in C:\Pact\securities-provider\oasexample.yaml:125 (from line 125 column 20 to column 44): Interpreting YAML !!timestamp as string
[oasexample.zip](https://github.com/grncdr/uri-template/files/8446420/oasexample.zip)

OpenAPI oasexample.yaml file is attached

**Comment by grncdr** [comment]
Sorry, I don't quite see how this has anything to do with this library. Could you clarify what the issue is?

**Comment by armen-ch** [comment]
Sorry, the issue was opened in the wrong project by mistake.
